apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-get
  labels:
    app: sw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw
  template:
    metadata:
      labels:
        app: sw
    spec:
      containers:
      - name: simple-watch
        image: quay.io/polynomial/simple-get@sha256:8a11c69ba425fc414f4caa6a7597d1dbb9caab03becb502b09079ac09184b800
